---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repos
      yum:
      name:
        update_cache: yes
      changed_when: False

  tasks:
    -include: task/packages.yml
    
- name: copy SSSD file
  copy:
    src: files/sssd_conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root


