- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      yum:
        update_cache: yes
      changed_when: False

  tasks:
    - include: Tasks/packages.yml
    - include: Tasks/scripts.yml
    - include: Tasks/users.yml
    - include: Tasks/configs.yml

