---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repos
      yum:
      name:
        update_cache: yes
      changed_when: False

  tasks:
    -include: task/packages.yml
    
- name: copy wallpaper file
  copy:
    src: files/file.png
    dest: /usr/share/
    owner: root
    group: root

- name: set wallpaper
