---
- hosts: all
  connection: local
  become: true
  
- name: checking updates
  yum:
    name: '*'
    security: yes
    state: latest
  check_mode: yes
  register: yum_output
        
  #pre_tasks:
  #  - name: update repos
   #   yum:
 #     name:
  #      update_cache: yes
  #    changed_when: False

  tasks:
    -include: Tasks/packages.yml
    
- name: copy SSSD file
  copy:
    src: Files/sssd_conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root


