- name: copy sssd_config
  copy:
    src: Files/sssd_conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0440

- name: copy Chrony
  copy:
    src: Files/chrony_conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0440

- name: copy smb_config
  copy:
    src: Files/smb_conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0440

- name: copy pam_duo_config
  copy:
    src: Files/pam_duo_conf
    dest: /etc/duo/pam_duo.conf
    owner: root
    group: root
    mode: 0440

- name: copy pam-password-auth
  copy:
    src: Files/pam_password-auth
    dest: /etc/pam.d/password-auth
    owner: root
    group: root
    mode: 0440

- name: copy sshd config
  copy:
    src: Files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0440
