- name: Install packages
  yum:
    name:
      - nano
      - realmd
      - sssd
      - oddjob
      - oddjob-mkhomedir
      - adcli
      - samba-common-tools
      - clamav
      - wget
      - openssl-devel
      - pam-devel
      - gcc
      - make
      - bzip2
      - selinux-policy-devel
